POST {{url}}/auth/signup
Content-Type: application/json
{
  "fullname": ".",
  "username": "valid@gmail.com",
  "password": "Bruh0!0!",
  "confirmPassword": "Bruh0!0!"
}


POST {{url}}/auth/login
Content-Type: application/json
{
  "username": "asd1",
  "password": "asd"
}

