# "username": "asd0",
# "_fullname": "Blanche Steuber",
# "_username": "asd1",
# "_fullname": "Doreen Prohaska",
# "password": "asd"

GET {{url}}/users
Authorization: {{asdToken0}}

GET {{url}}/users/{{asdId0}}
Authorization: {{asdToken0}}

GET {{url}}/users/{{asdId0}}/posts
Authorization: {{asdToken0}}

GET {{url}}/users/{{asdId1}}/messages
Authorization: {{asdToken0}}

########################################

GET {{url}}/users
Authorization: {{asdToken1}}

GET {{url}}/users/{{asdId1}}
Authorization: {{asdToken1}}

GET {{url}}/users/{{asdId1}}/posts
Authorization: {{asdToken1}}

GET {{url}}/users/{{asdId0}}/messages
Authorization: {{asdToken1}}

# GET {{url}}/users/{{asdId0}}/posts
# Authorization: {{asdToken0}}
