GET {{url}}/users
Authorization: {{asdToken0}}

GET {{url}}/users/{{asdId0}}
Authorization: {{asdToken0}}

GET {{url}}/users/{{asdId0}}/posts
Authorization: {{asdToken0}}

# GET {{url}}/users/{{asdId0}}/posts
# Authorization: {{asdToken0}}
