GET {{url}}/groups
Authorization: {{token}}

POST {{url}}/groups
Authorization: {{token}}
Content-Type: application/json
{
    "name": "meow meow",
    "public": "true",
    "bio": "",
    "avatarLink": ""
}

GET {{url}}/groups/{{group}}
Authorization: {{token}}

PUT {{url}}/groups/{{group}}
Authorization: {{token}}
Content-Type: application/json
{
    "name": "Lead Accounts j Designer", 
    "public": "false",
    "bio": "khong dieu kien",
    "avatarLink": "tai vi sao"
}

# TODO: this will be test last
DELETE {{url}}/groups/{{group}}
Authorization: {{token}}

GET {{url}}/groups/{{group}}/messages
Authorization: {{token}}

POST {{url}}/groups/{{group}}/messages
Authorization: {{token}}
Content-Type: application/json
{
    "content": "Khong dieu kien",
    "imageLink": ""
}

GET {{url}}/groups/{{group}}/members
Authorization: {{token}}

POST {{url}}/groups/{{group}}/members
Authorization: {{token}}

DELETE {{url}}/groups/{{group}}/members/{{member}}
Authorization: {{token}}

