# "username": "asd0",
# "_fullname": "Blanche Steuber",
# "_username": "asd1",
# "_fullname": "Doreen Prohaska",
# "password": "asd"

GET {{url}}/groups
Authorization: {{asdToken0}}

POST {{url}}/groups
Authorization: {{asdToken0}}
Content-Type: application/json
{
    "name": "dsbfhasdsasdu",
    "public": "true",
    "bio": "",
    "avatarLink": ""
}

GET {{url}}/groups/{{asdGroup0}}
Authorization: {{asdToken0}}

PUT {{url}}/groups/{{asdGroup0}}
Authorization: {{asdToken0}}
Content-Type: application/json
{
    "name": "Lead Accounts Designer", 
    "public": "false",
    "bio": "khong dieu kien",
    "avatarLink": "tai vi sao"
}

DELETE {{url}}/groups/{{asdGroup0}}
Authorization: {{asdToken0}}

########################################

GET {{url}}/groups
Authorization: {{asdToken1}}

POST {{url}}/groups
Authorization: {{asdToken1}}
Content-Type: application/json
{
    "name": "asd1 created this group",
    "public": "true",
    "bio": "",
    "avatarLink": ""
}

GET {{url}}/groups/{{asdGroup1}}
Authorization: {{asdToken1}}

PUT {{url}}/groups/{{asdGroup1}}
Authorization: {{asdToken1}}
Content-Type: application/json
{
    "name": "asd1 created this group0",
    "public": "true",
    "bio": "",
    "avatarLink": ""
}


# GET {{url}}/users/{{asdId0}}/posts
# Authorization: {{asdToken0}}
