GET {{url}}/users
Authorization: {{token}}

# 
GET {{url}}/users/{{other}}
Authorization: {{token}}

GET {{url}}/users/{{self}}
Authorization: {{token}}

# 
POST {{url}}/users/{{self}}/follows
Authorization: {{token}}

POST {{url}}/users/{{other}}/follows
Authorization: {{token}}

# only need to change token and switch run between other and self
# no need to change this manually
GET {{url}}/users/{{other}}/messages
Authorization: {{token}}

GET {{url}}/users/{{self}}/messages
Authorization: {{token}}

# 
POST {{url}}/users/{{other}}/messages
Authorization: {{token}}
Content-Type: application/json
{
    "content": "Khong dieu kien",
    "imageLink": ""
}

POST {{url}}/users/{{self}}/messages
Authorization: {{token}}
Content-Type: application/json
{
    "content": "Khong dieu kien",
    "imageLink": ""
}

#
GET {{url}}/users/{{other}}/posts
Authorization: {{token}}

GET {{url}}/users/{{self}}/posts
Authorization: {{token}}

# 
POST {{url}}/users/{{other}}/posts
Authorization: {{token}}
Content-Type: application/json
{
    "content": "Khong dieu kien"
}

POST {{url}}/users/{{self}}/posts
Authorization: {{token}}
Content-Type: application/json
{
    "content": "Khong dieu kien"
}

# 
POST {{url}}/users/{{self}}/posts/{{post}}/comments
Authorization: {{token}}
Content-Type: application/json
{
    "content": "tai vi sao"
}

# 
POST {{url}}/users/{{self}}/posts/{{post}}/comments/{{comment}}/likes
Authorization: {{token}}

